'use client';
import {useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import {ArrowRight,Plus,ArrowUpRight,Search,ChevronLeft,ChevronRight,BookOpen,Truck,Gift} from 'lucide-react';
import {useShop} from './shop-provider';
import {ProductArt,Book} from './book-art';
import {formatMoney} from '@/lib/commerce';
import {collection,type SortOrder} from '@/lib/collection';
export function LuxuryStorefront(){
 const{products,change,busy,connected,loading}=useShop();
 const[category,setCategory]=useState('All pieces'),[query,setQuery]=useState(''),[sort,setSort]=useState<SortOrder>('curated'),[page,setPage]=useState(1);
 const result=collection(products,category,query,sort,page);
 const count=(c:string)=>c==='All pieces'?products.length:products.filter(p=>p.category===c).length;
 function chooseCategory(c:string){setCategory(c);setPage(1);}
 function turnPage(n:number){setPage(n);document.getElementById('collection')?.scrollIntoView({behavior:'auto',block:'start'});}
 return <>
 <section className="luxury-hero"><div className="editorial-image"><Image src="/images/hero-editorial.png" alt="Blue and cream notebooks arranged on a desk" fill priority sizes="(max-width: 650px) 100vw, 72vw"/></div><div className="wrap luxury-hero-inner"><div className="luxury-hero-copy"><p className="hero-signature">The FolioVale paper collection</p><h1>For the thoughts<br/>worth keeping.</h1><p className="luxury-description">Notebooks for ideas. Planners for everyday.<br/>{' '}Space for notes, plans, and things worth keeping.</p><a className="brass-button" href="#collection">Explore the collection <ArrowRight size={18}/></a><a className="hero-secondary" href="#collection" onClick={()=>chooseCategory('Sets')}>Discover the sets</a></div><div className="hero-colophon"><span>Paper. Purpose. Possibility.</span><span>{products.length} pieces in the collection.</span></div></div></section>
 <div className="luxury-benefits wrap"><span><BookOpen size={18} strokeWidth={1.4}/> Designed around your everyday</span><span><Gift size={18} strokeWidth={1.4}/> Notebooks, planners &amp; sets</span><span><Truck size={19} strokeWidth={1.4}/> Delivery fee calculated at checkout · Free from ₦30,000</span></div>
 <section className="collection-intro wrap"><p>Some things deserve a place on paper.</p><h2>A little intention.<br/>In every page.</h2><div><p>For early ideas, long lists, and plans still taking shape. Find a notebook or planner that suits the way you write.</p><a className="text-link" href="#collection">Explore notebooks and planners <ArrowRight size={17}/></a></div></section>
 <section className="collection-doors wrap" aria-label="Shop by collection">{[
 {name:'Notebooks',copy:'Where ideas find their first home.',color:'#284f81',label:'the notebook',className:'door-notebooks'},
 {name:'Planners',copy:'A little structure. Your own pace.',color:'#9bb2bb',label:'the planner',className:'door-planners'},
 {name:'Sets',copy:'Thoughtful things, brought together.',color:'#445d75',label:'the collection',className:'door-sets'}
 ].map(c=><a key={c.name} href="#collection" className={'collection-door '+c.className} onClick={()=>chooseCategory(c.name)}><div className="door-books"><Book product={{color:c.color,cover_label:c.label,category:c.name as 'Notebooks'|'Planners'|'Sets'}}/>{c.name==='Sets'&&<Book product={{color:'#c5b69d',cover_label:'pocket notes',category:'Notebooks'}} small/>}</div><div className="door-copy"><span>{count(c.name)} pieces</span><h3>{c.name}</h3><p>{c.copy}</p><ArrowUpRight size={21} strokeWidth={1.4}/></div></a>)}</section>
 <section id="collection" className="collection luxury-collection wrap"><div className="section-heading"><div><p className="section-kicker">The full collection</p><h2>Find your next notebook.</h2></div><span className="collection-count">{products.length} pieces to explore.</span></div>
 <div className="collection-controls"><div className="category-tabs" role="group" aria-label="Filter the collection">{['All pieces','Notebooks','Planners','Sets'].map(c=><button key={c} aria-pressed={category===c} onClick={()=>chooseCategory(c)}>{c}<span>{count(c)}</span></button>)}</div><div className="search-sort"><label className="collection-search"><Search size={16}/><span className="sr-only">Search the collection</span><input type="search" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}} placeholder="Find a notebook, a planner…"/></label><label className="collection-sort"><span className="sr-only">Sort the collection</span><select value={sort} onChange={e=>{setSort(e.target.value as SortOrder);setPage(1);}}><option value="curated">Collection order</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="name">Name: A to Z</option></select></label></div></div>
 <p className="results-count" role="status">Showing {result.start}–{result.end} of {result.total} {category==='All pieces'?'pieces':category.toLowerCase()}</p>
 {result.total===0?<div className="empty-panel"><h3>No matching products.</h3><p>Try another name or browse the whole collection.</p><button className="text-link" onClick={()=>{setQuery('');chooseCategory('All pieces');}}>Clear filters</button></div>:
 <div className="product-grid luxury-product-grid">{result.items.map(p=><article className="product-card" key={p.id}><Link href={'/products/'+p.slug} className="product-image-link"><ProductArt product={p}/><span className="product-view"><ArrowUpRight size={19}/><span className="sr-only">View {p.name}</span></span>{p.stock===0&&<span className="stock-tag">Sold out</span>}</Link><div className="product-meta"><span>{p.category}</span><span>{p.category==='Sets'?'The paper collection':p.specs[0].split(' · ')[0]}</span></div><div className="product-name-line"><h3><Link href={'/products/'+p.slug}>{p.name}</Link></h3><strong>{formatMoney(p.price_kobo)}</strong></div><p className="product-subtitle">{p.subtitle}</p><button className="add-button" disabled={loading||busy||!connected||p.stock===0} onClick={()=>void change(p.id,1,'add')}><span>{p.stock===0?'Sold out':'Add to cart'}</span><Plus size={16}/></button></article>)}</div>}
 {result.pages>1&&<nav className="pagination" aria-label="Collection pages"><button disabled={result.current===1} onClick={()=>turnPage(result.current-1)} aria-label="Previous page"><ChevronLeft size={17}/></button>{Array.from({length:result.pages},(_,i)=><button key={i+1} aria-label={'Page '+(i+1)} aria-current={result.current===i+1?'page':undefined} onClick={()=>turnPage(i+1)}>{i+1}</button>)}<button disabled={result.current===result.pages} onClick={()=>turnPage(result.current+1)} aria-label="Next page"><ChevronRight size={17}/></button></nav>}
 </section>
 <section id="our-story" className="luxury-story wrap"><div className="story-paper"><div className="paper-page"><span>From the desk<br/>of FolioVale</span><p>Give your ideas<br/>somewhere<br/>to belong.</p><div className="paper-signature">FolioVale</div></div></div><div className="luxury-story-copy"><p className="section-kicker">A note from our desk</p><h2>The everyday,<br/>made meaningful.</h2><p>A notebook is a small thing. But it can hold the start of something important: a first idea, a thoughtful plan, a few words you do not want to forget.</p><p>FolioVale is a collection of paper companions for those moments. Quiet colours, a choice of formats, and room to make them your own.</p><Link href="/shipping" className="text-link">Get to know FolioVale <ArrowRight size={17}/></Link></div></section>
 </>;
}
