'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Check,ArrowRight,Package,Mail} from 'lucide-react';
import {useShop,request} from './shop-provider';
import {formatMoney} from '@/lib/commerce';
import type {Order} from '@/lib/types';
const date=(value:string)=>new Intl.DateTimeFormat('en-NG',{day:'numeric',month:'long',year:'numeric'}).format(new Date(value));
export function OrderHistory(){
 const{user,loading,signIn,signOut}=useShop();const[orders,setOrders]=useState<Order[]>([]),[error,setError]=useState(''),[fetching,setFetching]=useState(true);
 useEffect(()=>{if(!user){setFetching(false);return;}setFetching(true);request<{orders:Order[]}>('/api/orders').then(d=>setOrders(d.orders)).catch(e=>setError(e.message)).finally(()=>setFetching(false));},[user]);
 return <section className="wrap page-shell orders-page"><div className="section-heading"><div><p className="section-kicker">Your paper trail</p><h1>Your orders.</h1></div>{user&&<button className="quiet-button underline" onClick={()=>void signOut()}>Sign out</button>}</div>
 {loading||fetching?<p>Loading your orders…</p>:!user?<div className="empty-panel"><Package size={40}/><h2>Your collection starts here.</h2><p>Sign in with Google to see your order history.</p><button className="google-button" onClick={()=>void signIn('/orders')}><span className="google-g">G</span>Continue with Google</button></div>:error?<p role="alert" className="form-error">{error}</p>:orders.length===0?<div className="empty-panel"><h2>No orders just yet.</h2><p>Find a fresh page to start with.</p><Link className="primary-button" href="/#collection">Explore the collection</Link></div>:<div className="order-list">{orders.map(order=><Link className="order-row" key={order.id} href={'/orders/'+order.id}><div><strong>{order.reference}</strong><p>{date(order.created_at)} · {order.items.reduce((n,i)=>n+i.quantity,0)} items</p></div><span className="status-chip">Order placed</span><strong>{formatMoney(order.total_kobo)}</strong><ArrowRight size={19}/></Link>)}</div>}</section>;
}
export function OrderDetail({id}:{id:string}){
 const{user,loading,signIn}=useShop();const[order,setOrder]=useState<Order|null>(null),[error,setError]=useState(''),[emailMessage,setEmailMessage]=useState(''),[retrying,setRetrying]=useState(false);
 useEffect(()=>{if(user)request<{order:Order}>('/api/orders/'+id).then(d=>setOrder(d.order)).catch(e=>setError(e.message));},[user,id]);
 async function retry(){setRetrying(true);try{const data=await request<{email_status:Order['email_status']}>('/api/orders/'+id+'/email',{});setOrder(o=>o?{...o,email_status:data.email_status}:o);setEmailMessage(data.email_status==='accepted'?'The email has been accepted for delivery.':'Your order is saved. Email is still pending; please wait a minute before retrying.');}catch(e){setEmailMessage(e instanceof Error?e.message:'Please try again later.');}finally{setRetrying(false);}}
 if(loading)return <div className="wrap page-shell">Loading your order…</div>;
 if(!user)return <section className="wrap page-shell empty-panel"><h1>Sign in to view your order.</h1><button className="google-button" onClick={()=>void signIn('/orders')}>Continue with Google</button></section>;
 if(error)return <section className="wrap page-shell"><p className="form-error" role="alert">{error}</p><Link href="/orders">Back to your orders</Link></section>;
 if(!order)return <div className="wrap page-shell">Loading your order…</div>;
 return <section className="wrap page-shell confirmation-page"><div className="confirmation-heading"><span className="success-mark"><Check size={28}/></span><p className="section-kicker">Order {order.reference}</p><h1>Good things are on the page.</h1><p>Your order has been recorded, {order.full_name.split(' ')[0]}.</p><span className="status-chip">Order placed · Pay on delivery</span></div>
 <div className="confirmation-grid"><div className="order-summary"><h2>Your order</h2>{order.items.map(item=><div className="receipt-item" key={item.product_id}><div><strong>{item.product_name}</strong><p>Qty {item.quantity} · {formatMoney(item.unit_price_kobo)} each</p></div><strong>{formatMoney(item.quantity*item.unit_price_kobo)}</strong></div>)}<div className="summary-totals"><p><span>Delivery</span><span>{order.shipping_kobo?formatMoney(order.shipping_kobo):'Free'}</span></p><p className="total-line"><strong>Total</strong><strong>{formatMoney(order.total_kobo)}</strong></p></div></div><div className="confirmation-details"><h2>Delivery details</h2><p>{order.full_name}<br/>{order.address}<br/>{order.city}, {order.state}<br/>{order.phone}</p>{order.notes&&<p className="delivery-note">{order.notes}</p>}<h2><Mail size={19}/> Confirmation email</h2><p>{order.email_status==='accepted'?'Your confirmation was accepted for delivery to ':order.email_status==='sending'?'Your confirmation email is being processed for ':'Your order is saved. A confirmation email is pending for '}{order.email}.</p>{['queued','failed'].includes(order.email_status)&&<button className="text-link" disabled={retrying} onClick={()=>void retry()}>{retrying?'Trying…':'Retry confirmation email'}</button>}{emailMessage&&<p role="status" className="small">{emailMessage}</p>}</div></div><p className="demo-note">Test order recorded. No payment was taken; dispatch is not available during testing.</p><div className="confirmation-actions"><Link className="primary-button" href="/#collection">Back to the collection <ArrowRight size={18}/></Link><Link className="text-link" href="/orders">View all orders</Link></div></section>;
}
