-- Correct grammar/capitalization in exactly 21 catalogue descriptions.
-- Data-only migration: no product identity, pricing, stock or specifications change.
-- Match stable UUID, slug and previous copy; preserve independently edited rows.
-- Already-corrected rows are skipped, making repeat execution harmless.
BEGIN;
WITH corrections (id, slug, old_description, new_description) AS (
  VALUES
  ('10000000-0000-4000-8000-000000000007', 'aster', 'A A5 ruled notebook with 192 pages for daily notes, longer thoughts, and everyday lists. 100 gsm paper and a cloth-style cover give your ideas a considered home.', 'An A5 ruled notebook with 192 pages for daily notes, longer thoughts, and everyday lists. 100 gsm paper and a cloth-style cover give your ideas a considered home.'),
  ('10000000-0000-4000-8000-000000000009', 'nocturne', 'A A5 ruled notebook with 240 pages for daily notes, longer thoughts, and everyday lists. 100 gsm paper and a cloth-style cover give your ideas a considered home.', 'An A5 ruled notebook with 240 pages for daily notes, longer thoughts, and everyday lists. 100 gsm paper and a cloth-style cover give your ideas a considered home.'),
  ('10000000-0000-4000-8000-000000000010', 'harbour', 'A A5 plain notebook with 160 pages for sketching, free writing, and ideas that need an open page. 100 gsm paper and a cloth-style cover give your ideas a considered home.', 'An A5 plain notebook with 160 pages for sketching, free writing, and ideas that need an open page. 100 gsm paper and a cloth-style cover give your ideas a considered home.'),
  ('10000000-0000-4000-8000-000000000011', 'atlas', 'A A4 dot-grid notebook with 160 pages for bullet journals, diagrams, and flexible layouts. 120 gsm paper and a cloth-style cover give your ideas a considered home.', 'An A4 dot-grid notebook with 160 pages for bullet journals, diagrams, and flexible layouts. 120 gsm paper and a cloth-style cover give your ideas a considered home.'),
  ('10000000-0000-4000-8000-000000000012', 'field-notes', 'A A6 ruled notebook with 96 pages for daily notes, longer thoughts, and everyday lists. 90 gsm paper and a cloth-style cover give your ideas a considered home.', 'An A6 ruled notebook with 96 pages for daily notes, longer thoughts, and everyday lists. 90 gsm paper and a cloth-style cover give your ideas a considered home.'),
  ('10000000-0000-4000-8000-000000000014', 'studio', 'A A5 plain notebook with 128 pages for sketching, free writing, and ideas that need an open page. 140 gsm paper and a cloth-style cover give your ideas a considered home.', 'An A5 plain notebook with 128 pages for sketching, free writing, and ideas that need an open page. 140 gsm paper and a cloth-style cover give your ideas a considered home.'),
  ('10000000-0000-4000-8000-000000000015', 'letters', 'A A5 ruled notebook with 192 pages for daily notes, longer thoughts, and everyday lists. 100 gsm paper and a cloth-style cover give your ideas a considered home.', 'An A5 ruled notebook with 192 pages for daily notes, longer thoughts, and everyday lists. 100 gsm paper and a cloth-style cover give your ideas a considered home.'),
  ('10000000-0000-4000-8000-000000000017', 'mosaic', 'A A5 dot-grid notebook with 192 pages for bullet journals, diagrams, and flexible layouts. 100 gsm paper and a cloth-style cover give your ideas a considered home.', 'An A5 dot-grid notebook with 192 pages for bullet journals, diagrams, and flexible layouts. 100 gsm paper and a cloth-style cover give your ideas a considered home.'),
  ('10000000-0000-4000-8000-000000000018', 'coastline', 'A A5 ruled notebook with 160 pages for daily notes, longer thoughts, and everyday lists. 100 gsm paper and a cloth-style cover give your ideas a considered home.', 'An A5 ruled notebook with 160 pages for daily notes, longer thoughts, and everyday lists. 100 gsm paper and a cloth-style cover give your ideas a considered home.'),
  ('10000000-0000-4000-8000-000000000019', 'stillwater', 'A A5 plain notebook with 192 pages for sketching, free writing, and ideas that need an open page. 100 gsm paper and a cloth-style cover give your ideas a considered home.', 'An A5 plain notebook with 192 pages for sketching, free writing, and ideas that need an open page. 100 gsm paper and a cloth-style cover give your ideas a considered home.'),
  ('10000000-0000-4000-8000-000000000020', 'linen', 'A A5 ruled notebook with 192 pages for daily notes, longer thoughts, and everyday lists. 100 gsm paper and a cloth-style cover give your ideas a considered home.', 'An A5 ruled notebook with 192 pages for daily notes, longer thoughts, and everyday lists. 100 gsm paper and a cloth-style cover give your ideas a considered home.'),
  ('10000000-0000-4000-8000-000000000021', 'graphite', 'A A4 plain notebook with 96 pages for sketching, free writing, and ideas that need an open page. 160 gsm paper and a cloth-style cover give your ideas a considered home.', 'An A4 plain notebook with 96 pages for sketching, free writing, and ideas that need an open page. 160 gsm paper and a cloth-style cover give your ideas a considered home.'),
  ('10000000-0000-4000-8000-000000000022', 'meadow', 'A A5 dot-grid notebook with 160 pages for bullet journals, diagrams, and flexible layouts. 100 gsm paper and a cloth-style cover give your ideas a considered home.', 'An A5 dot-grid notebook with 160 pages for bullet journals, diagrams, and flexible layouts. 100 gsm paper and a cloth-style cover give your ideas a considered home.'),
  ('10000000-0000-4000-8000-000000000025', 'moonlit', 'A A5 dot-grid notebook with 192 pages for bullet journals, diagrams, and flexible layouts. 100 gsm paper and a cloth-style cover give your ideas a considered home.', 'An A5 dot-grid notebook with 192 pages for bullet journals, diagrams, and flexible layouts. 100 gsm paper and a cloth-style cover give your ideas a considered home.'),
  ('10000000-0000-4000-8000-000000000026', 'everyday', 'A A5 ruled notebook with 128 pages for daily notes, longer thoughts, and everyday lists. 90 gsm paper and a cloth-style cover give your ideas a considered home.', 'An A5 ruled notebook with 128 pages for daily notes, longer thoughts, and everyday lists. 90 gsm paper and a cloth-style cover give your ideas a considered home.'),
  ('10000000-0000-4000-8000-000000000027', 'folio', 'A A4 grid notebook with 192 pages for diagrams, calculations, and structured notes. 100 gsm paper and a cloth-style cover give your ideas a considered home.', 'An A4 grid notebook with 192 pages for diagrams, calculations, and structured notes. 100 gsm paper and a cloth-style cover give your ideas a considered home.'),
  ('10000000-0000-4000-8000-000000000045', 'writing-pair', 'A coordinated stationery set for planning, writing, and everyday ideas. Includes one A5 Aster ruled notebook, plus one a6 field notes notebook. Presented together so it is ready for a fresh start.', 'A coordinated stationery set for planning, writing, and everyday ideas. Includes one A5 Aster ruled notebook, plus one A6 Field Notes notebook. Presented together so it is ready for a fresh start.'),
  ('10000000-0000-4000-8000-000000000046', 'planner-pair', 'A coordinated stationery set for planning, writing, and everyday ideas. Includes one A5 Weekender planner, plus one a5 daybook notebook. Presented together so it is ready for a fresh start.', 'A coordinated stationery set for planning, writing, and everyday ideas. Includes one A5 Weekender planner, plus one A5 Daybook notebook. Presented together so it is ready for a fresh start.'),
  ('10000000-0000-4000-8000-000000000048', 'studio-set', 'A coordinated stationery set for sketching and creative work. Includes one A5 Studio plain notebook, plus one a4 graphite sketchbook. Presented together so it is ready for a fresh start.', 'A coordinated stationery set for sketching and creative work. Includes one A5 Studio plain notebook, plus one A4 Graphite sketchbook. Presented together so it is ready for a fresh start.'),
  ('10000000-0000-4000-8000-000000000049', 'daily-ritual', 'A coordinated stationery set for planning, writing, and everyday ideas. Includes one A5 First Light daily planner, plus one a6 pocket notes notebook. Presented together so it is ready for a fresh start.', 'A coordinated stationery set for planning, writing, and everyday ideas. Includes one A5 First Light daily planner, plus one A6 Pocket Notes notebook. Presented together so it is ready for a fresh start.'),
  ('10000000-0000-4000-8000-000000000051', 'workday-edit', 'A coordinated stationery set for planning, writing, and everyday ideas. Includes one B5 Archive notebook, plus one a5 focus daily planner. Presented together so it is ready for a fresh start.', 'A coordinated stationery set for planning, writing, and everyday ideas. Includes one B5 Archive notebook, plus one A5 Focus daily planner. Presented together so it is ready for a fresh start.')
)
UPDATE public.products AS p
SET description = c.new_description
FROM corrections AS c
WHERE p.id = c.id::uuid
  AND p.slug = c.slug
  AND p.description = c.old_description
RETURNING p.id, p.name;
COMMIT;
